name: JosekiOthello
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    MARKETING_VERSION: "1.1"
    CURRENT_PROJECT_VERSION: 2
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: 83VGKGSQUH
    CODE_SIGN_STYLE: Automatic
targets:
  JosekiOthello:
    type: application
    platform: iOS
    sources: [JosekiOthello]
    settings:
      base:
        INFOPLIST_FILE: JosekiOthello/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.josekiothello
        TARGETED_DEVICE_FAMILY: "1,2"
