name: JosekiOthello
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: 83VGKGSQUH
    CODE_SIGN_STYLE: Automatic
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: "11.13.0"
targets:
  JosekiOthello:
    type: application
    platform: iOS
    sources: [JosekiOthello]
    settings:
      base:
        INFOPLIST_FILE: JosekiOthello/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.josekiothello
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: GoogleMobileAds
